// Default location: lib/models/message.dart
// Message model to represent chat messages in the application

enum MessageRole { user, assistant, system }

class Message {
  static const Object _unset = Object();

  final String id;
  final MessageRole role;
  final String content;
  final String? thinkingContent; // Thinking model reasoning (e.g., DeepSeek R1)
  final DateTime timestamp;
  final String? imageUrl; // Optional image attachment
  final String? title; // Optional message title generated by AI
  final String sessionId; // Session ID to group messages
  final int? promptTokens;
  final int? completionTokens;
  final double? cost;

  Message({
    required this.id,
    required this.role,
    required this.content,
    this.thinkingContent,
    required this.timestamp,
    this.imageUrl,
    this.title,
    required this.sessionId,
    this.promptTokens,
    this.completionTokens,
    this.cost,
  });

  int? get totalTokens {
    if (promptTokens == null && completionTokens == null) {
      return null;
    }
    return (promptTokens ?? 0) + (completionTokens ?? 0);
  }

  String? get formattedCost =>
      cost == null ? null : '\$${cost!.toStringAsFixed(6)}';

  // Convert Message to JSON format for storage
  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'role': role.toString().split('.').last,
      'content': content,
      'thinkingContent': thinkingContent,
      'timestamp': timestamp.millisecondsSinceEpoch,
      'imageUrl': imageUrl,
      'title': title,
      'sessionId': sessionId,
      'promptTokens': promptTokens,
      'completionTokens': completionTokens,
      'cost': cost,
    };
  }

  // Convert Message to JSON format for API requests
  Map<String, dynamic> toApiJson() {
    // If there's an image URL, we need special handling
    if (imageUrl != null && role == MessageRole.user) {
      // If content is empty, only send image
      if (content.trim().isEmpty) {
        return {
          'role': 'user',
          'content': [
            {
              'type': 'image_url',
              'image_url': {'url': imageUrl!, 'detail': 'auto'}
            }
          ]
        };
      } else {
        // Both content and image exist
        return {
          'role': 'user',
          'content': [
            {'type': 'text', 'text': content},
            {
              'type': 'image_url',
              'image_url': {'url': imageUrl!, 'detail': 'auto'}
            }
          ]
        };
      }
    }
    // Regular text message
    return {
      'role': role.toString().split('.').last,
      'content': content,
    };
  }

  // Create full JSON for storage
  Map<String, dynamic> toFullJson() => toJson();

  // Create a Message from JSON response
  factory Message.fromJson(Map<String, dynamic> json) {
    return Message(
      id: json['id'] ?? DateTime.now().millisecondsSinceEpoch.toString(),
      role: _roleFromString(json['role']?.toString() ?? 'user'),
      content: json['content'],
      thinkingContent: json['thinkingContent'],
      timestamp: json['timestamp'] != null
          ? DateTime.fromMillisecondsSinceEpoch(json['timestamp'])
          : DateTime.now(),
      imageUrl: json['image_url'] ?? json['imageUrl'],
      title: json['title'],
      sessionId: json['sessionId'] ?? 'default',
      promptTokens: _intFromJson(json['prompt_tokens'] ?? json['promptTokens']),
      completionTokens:
          _intFromJson(json['completion_tokens'] ?? json['completionTokens']),
      cost: _doubleFromJson(json['cost']),
    );
  }

  Message copyWith({
    String? id,
    MessageRole? role,
    String? content,
    Object? thinkingContent = _unset,
    DateTime? timestamp,
    Object? imageUrl = _unset,
    Object? title = _unset,
    String? sessionId,
    Object? promptTokens = _unset,
    Object? completionTokens = _unset,
    Object? cost = _unset,
  }) {
    return Message(
      id: id ?? this.id,
      role: role ?? this.role,
      content: content ?? this.content,
      thinkingContent: identical(thinkingContent, _unset)
          ? this.thinkingContent
          : thinkingContent as String?,
      timestamp: timestamp ?? this.timestamp,
      imageUrl: identical(imageUrl, _unset)
          ? this.imageUrl
          : imageUrl as String?,
      title: identical(title, _unset) ? this.title : title as String?,
      sessionId: sessionId ?? this.sessionId,
      promptTokens: identical(promptTokens, _unset)
          ? this.promptTokens
          : promptTokens as int?,
      completionTokens: identical(completionTokens, _unset)
          ? this.completionTokens
          : completionTokens as int?,
      cost: identical(cost, _unset) ? this.cost : cost as double?,
    );
  }

  // Helper method to convert string to MessageRole enum
  static MessageRole _roleFromString(String role) {
    switch (role) {
      case 'user':
        return MessageRole.user;
      case 'assistant':
        return MessageRole.assistant;
      case 'system':
        return MessageRole.system;
      default:
        return MessageRole.user;
    }
  }

  static int? _intFromJson(dynamic value) {
    if (value == null) {
      return null;
    }
    if (value is int) {
      return value;
    }
    if (value is num) {
      return value.toInt();
    }
    if (value is String) {
      return int.tryParse(value);
    }
    return null;
  }

  static double? _doubleFromJson(dynamic value) {
    if (value == null) {
      return null;
    }
    if (value is double) {
      return value;
    }
    if (value is num) {
      return value.toDouble();
    }
    if (value is String) {
      return double.tryParse(value);
    }
    return null;
  }
}
