name: Build and Release Flutter APK

on:
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies for Flutter
        run: sudo apt-get update && sudo apt-get install -y curl unzip xz-utils zip libglu1-mesa apksigner

      - name: Download Flutter SDK
        run: |
          curl -o flutter.tar.xz https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.22.0-stable.tar.xz
          tar -xf flutter.tar.xz
          echo "$PWD/flutter/bin" >> $GITHUB_PATH

      - name: Verify Flutter installation
        run: |
          flutter channel stable
          flutter upgrade
          flutter --version

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Install Flutter project
        run: flutter create .

      - name: Keystore'u oluştur
        run: echo "${{ secrets.ANDROID_KEYSTORE }}" | base64 -d > android/app/my-release-key.jks

      - name: key.properties oluştur
        run: |
          echo "storePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.ANDROID_KEYSTORE_ALIAS }}" >> android/key.properties
          echo "storeFile=android/app/my-release-key.jks" >> android/key.properties

      - name: Build APK (all platform)
        run: flutter build apk --release

      - name: Build release APK
        run: flutter build apk --release

      - name: APK imza sertifika bilgilerini göster
        run: |
          echo "----------- APK İMZA DETAYLARI -----------"
          apksigner verify --print-certs build/app/outputs/flutter-apk/app-release.apk
          echo " "
          echo "----------- RSA .dname BİLGİSİ -----------"
          unzip -p build/app/outputs/flutter-apk/app-release.apk META-INF/*.RSA > CERT.RSA
          keytool -printcert -file CERT.RSA

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}  # örnek: v12
          release_name: Release v${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Upload APK to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/app/outputs/flutter-apk/app-release.apk
          asset_name: app-release.apk
          asset_content_type: application/vnd.android.package-archive
