name: Build and Tag Flutter APK for android arm64-v8a

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-tag:
    runs-on: ubuntu-latest

    steps:
      # 1. Depoyu Klonlama
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Flutter Gereksinimlerini Yükleme
      - name: Install dependencies for Flutter
        run: sudo apt-get update && sudo apt-get install -y curl unzip xz-utils zip libglu1-mesa

      # 3. Flutter SDK'yı İndirme
      - name: Download Flutter SDK
        run: |
          curl -o flutter.tar.xz https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.22.0-stable.tar.xz
          tar -xf flutter.tar.xz
          echo "$PWD/flutter/bin" >> $GITHUB_PATH

      # 4. Flutter Kurulumunu Doğrulama
      - name: Verify Flutter installation
        run: flutter --version

      # 5. Flutter Bağımlılıklarını Yükleme
      - name: Install Flutter dependencies
        run: flutter pub get

      # 6. Projeyi Oluşturma
      - name: Build APK (arm64-v8a)
        run: flutter build apk --release --target-platform=android-arm64

      # 7. Yeni Tag Oluşturma
      - name: Create Git Tag
        run: |
          TAG_NAME="v1.0.${{ github.run_number }}"
          git tag $TAG_NAME
          git push origin $TAG_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 8. Build Cache'i Temizleme
      - name: Clean flutter build cache
        run: flutter clean
