name: Keystore Oluştur ve Tek Satırlı base64 Al

on:
  workflow_dispatch:

jobs:
  create-keystore:
    runs-on: ubuntu-latest
    steps:
      - name: Keystore dosyası oluştur
        run: |
          keytool -genkeypair \
            -keystore my-release-key.jks \
            -storepass my-store-password \
            -keypass my-key-password \
            -alias my-key-alias \
            -dname "CN=Fatih Kartal, OU=EEM, O=bruhmomentumtr, L=USAK, S=USAK, C=TR" \
            -keyalg RSA -keysize 2048 -validity 10000

      - name: Keystore'u base64'e encode et (tek satırlı)
        run: |
          base64 -w 0 my-release-key.jks > base64_keystore.txt
          echo "----- BUNU SECRET'A TEK SATIR OLARAK YAPIŞTIR -----"
          echo "ANDROID_KEYSTORE"
          cat base64_keystore.txt
