name: Create & Output Keystore

on:
  workflow_dispatch: # Elle tetikleme için

jobs:
  create-keystore:
    runs-on: ubuntu-latest
    steps:
      - name: Repo checkout
        uses: actions/checkout@v4

      - name: Keystore oluştur
        run: |
          keytool -genkey -v \
            -keystore my-release-key.jks \
            -keyalg RSA -keysize 2048 -validity 10000 \
            -alias my-key-alias \
            -storepass my-store-password \
            -keypass my-key-password \
            -dname "CN=John Doe, OU=Dev, O=Company, L=Istanbul, S=TR, C=TR"

      - name: Keystore'u base64 ile şifrele
        run: |
          base64 my-release-key.jks > keystore.b64

      - name: Base64 içeriği göster
        run: |
          echo "BU SATIRI KOPYALA VE SECRETS'A EKLE:"
          cat keystore.b64
